[tool.poetry]
name = "python-tool-template"
version = "0.1.0"
description = "A template repository for building tools in Python"
readme = "README.md"
authors = ["Luc Shelton <lucshelton@gmail.com>"]
homepage = "https://github.com/loveduckie/python-tool-template"
repository = "https://github.com/loveduckie/python-tool-template"
documentation = "https://github.com/loveduckie/python-tool-template/-/wikis/home"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
packages = [
    { include = "python_tool_template" },
    { include = "python_tool_template_tests" }
]

[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.8.1"
rich-click = "^1.8.3"
click = "^8.1.7"


[tool.poetry.scripts]
python-tool-template = 'python_tool_template.__main__:cli'

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.poetry.group.docs.dependencies]
sphinx = "^7.4.4"
sphinx-rtd-theme = "^2.0.0"


[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
pylint = "^3.2.5"


[tool.poetry.group.test.dependencies]
coverage = "^7.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry_bumpversion.file."python_tool_template/__init__.py"]
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'